### PR TITLE
Updated to latest version of schnorrkel

### PR DESCRIPTION
**Pull request by gautamdhameja**

### CODE REVIEW

**Comment by gautamdhameja** [comment]
I am getting an issue with the generated binary after these changes. If I compile in debug mode then the `sr25519_verify` fn returns true or false as expected, but when I compile in the release mode then it returns true even with negative tests. Any ideas? @Warchant

**Comment by Warchant** [comment]
Will check.

**UPD**: did you build C tests? You can do this with cmake flag `-DTESTING=ON` (`cmake .. -DTESTING=ON`). It is off by default to not force users download and build gtest/gmock.

It seems schnorrkel has some breaking changes, and our tests fail now.

List of failed tests:
- DeriveHardKnown
- DeriveSoftKnown
- VerifyExisting
- KeypairFromSeed
- ResultNotLess

**UPD2**: `cargo test` passes for both debug and release modes.

**UPD3**: internals of sr25519 implementation also [changed](https://sourcegraph.com/github.com/polkadot-js/wasm@jg-schnorrkel-0.8/-/blob/packages/wasm-crypto/src/sr25519.rs#L36). We will update soon.

**Comment by gautamdhameja** [comment]
Yeah, it seems there are some more changes needed as the internals have changed a bit. Thanks for taking a look and for sharing pointers, @Warchant.
I am using the `dll` generated by this library to create dotnet bindings for sr25519. For now, I'll use the current master (0.1.1).

**Comment by Warchant** [comment]
@gautamdhameja yeah, it is safe to use latest release version. We follow semver, so when we fix everything and update version, new major version will be released.

**Comment by burdges** [comment]
We changed the scalar serialization for secret keys from ed25519 to canonical styles, which might break any tests anywhere.  If your code is not deployed, then fix any secret keys by shifting the scalar left 3 bits, ala `scalars::divide_scalar_bytes_by_cofactor`.  We also have some `from*_ed25519_bytes` mothods for if code is deployed.  Any test vector called KeypairFromSeed should be broken by this, even if you use `ExpansionMode::Ed25519`.

I'd expect DeriveHardKnown should work if using the `ExpansionMode::Ed25519`.  I kinda hate this mode existing, but we've too many people with keys derived this way for kusama, maybe we'll restrict to `ExpansionMode::Uniform` for polkadot, or maybe we'll give up and keep it this way.

There are no changes that break the actual soft derivation behind DeriveSoftKnown in 0.8.4 but the previous yanked 0.8.* broke this by mistake, so ignore any failures before 0.8.4.

I'd expect VerifyExisting would work if you employ the preaudit_deprecated feature, but this should disapear once all testnets update, so again just replace the test vector if the code is not deplotyed.

I'm unsure what ResultNotLess does.

cc @jacogr

**Pull request closed without merging**
